import { useEffect, useMemo, useState } from 'react';
import './admin.css';
import ProjectBuilder from './ProjectBuilder';

const API = import.meta.env.VITE_API_BASE_URL || '/api';
const request = async (path, options={}) => { const r=await fetch(`${API}${path}`,options); const d=await r.json().catch(()=>({})); if(!r.ok) throw new Error(d.message||`Error ${r.status}`); return d; };
const json=(method,body,headers)=>({method,headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body)});
const Field=({label,...p})=><label className="adminField"><span>{label}</span><input {...p}/></label>;
const Notice=({children})=>children?<div className="adminNotice">{children}</div>:null;
function Login({title,subtitle,value,setValue,onSubmit,error,onBack}){return <main className="adminLogin"><div className="loginBox"><span className="adminLogo">RE</span><span className="adminKicker">REALESTATE PLATFORM</span><h1>{title}</h1><p>{subtitle}</p><form onSubmit={e=>{e.preventDefault();onSubmit()}}><Field label="Clave de acceso" type="password" value={value} onChange={e=>setValue(e.target.value)} required/><button className="adminPrimary">Entrar</button></form><Notice>{error}</Notice><button className="adminGhost" onClick={onBack}>← Volver</button></div></main>}
function Shell({brand,subtitle,onBack,children}){return <div className="adminApp"><header className="adminHeader"><div><b>RE</b><strong>{brand}</strong><small>{subtitle}</small></div><button className="adminGhost" onClick={onBack}>Salir</button></header>{children}</div>}
function TenantPortal({apiKey,onLogout}){const headers=useMemo(()=>({'x-api-key':apiKey}),[apiKey]);const [company,setCompany]=useState(null),[projects,setProjects]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState({name:'',slug:'',description:''}),[error,setError]=useState('');const load=async()=>{const [me,list]=await Promise.all([request('/admin/me',{headers}),request('/admin/projects',{headers})]);setCompany(me);setProjects(list)};useEffect(()=>{load().catch(e=>setError(e.message))},[apiKey]);const create=async e=>{e.preventDefault();try{const p=await request('/admin/projects',json('POST',form,headers));setForm({name:'',slug:'',description:''});await load();setSelected(p)}catch(e){setError(e.message)}};if(selected)return <ProjectBuilder project={selected} apiKey={apiKey} onRefresh={load} onBack={()=>setSelected(null)}/>;return <Shell brand={company?.name||'Constructora'} subtitle="Workspace" onBack={onLogout}><main className="adminMain"><div className="workspaceHead"><div><span className="adminKicker">CLIENT WORKSPACE</span><h1>Proyectos</h1><p>Fuente única para estructura, inventario, contenido, IA, experiencia y publicación.</p></div></div><Notice>{error}</Notice><div className="contentGrid"><article className="adminPanel"><span className="adminKicker">NUEVO PROYECTO</span><h2>Crear showroom</h2><form onSubmit={create}><Field label="Nombre" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><Field label="Slug" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><label className="adminField"><span>Descripción</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="adminPrimary">Crear proyecto</button></form></article><article className="adminPanel"><span className="adminKicker">MIS PROYECTOS</span><h2>{projects.length} proyectos</h2>{projects.map(p=><button className="projectCard" key={p.id} onClick={()=>setSelected(p)}><b>{p.name}</b><span>{p.slug}</span><em>{p.status}</em></button>)}</article></div></main></Shell>}
function PlatformPortal({platformKey,onLogout}){const headers=useMemo(()=>({'x-platform-key':platformKey}),[platformKey]);const [companies,setCompanies]=useState([]),[projects,setProjects]=useState([]),[error,setError]=useState('');useEffect(()=>{request('/admin/companies',{headers}).then(async c=>{setCompanies(c);const groups=await Promise.all(c.map(company=>request(`/platform/companies/${company.id}/projects`,{headers}).catch(()=>[])));setProjects(groups.flat())}).catch(e=>setError(e.message))},[platformKey]);return <Shell brand="Platform Owner" subtitle="Control central" onBack={onLogout}><main className="adminMain"><div className="workspaceHead"><div><span className="adminKicker">PLATFORM CONTROL</span><h1>Operación</h1><p>Empresas, proyectos y estado global.</p></div></div><Notice>{error}</Notice><div className="adminStats"><div><strong>{companies.length}</strong><span>Empresas</span></div><div><strong>{projects.length}</strong><span>Proyectos</span></div></div><div className="contentGrid"><article className="adminPanel"><span className="adminKicker">TENANTS</span><h2>Empresas</h2>{companies.map(c=><div className="dataRow" key={c.id}><b>{c.name}</b><span>{c.slug}</span><em>{c.status}</em></div>)}</article><article className="adminPanel"><span className="adminKicker">PROYECTOS</span><h2>Global</h2>{projects.map(p=><div className="dataRow" key={p.id}><b>{p.name}</b><span>{p.slug}</span><em>{p.status}</em></div>)}</article></div></main></Shell>}
export default function AdminPortal(){const [mode,setMode]=useState(null),[key,setKey]=useState(''),[error,setError]=useState('');const reset=()=>{setMode(null);setKey('');setError('')};if(!mode)return <main className="adminLogin"><div className="loginBox"><span className="adminLogo">RE</span><span className="adminKicker">REALESTATE PLATFORM</span><h1>Control del showroom</h1><p>Elegí el acceso.</p><div className="contentGrid"><button className="adminPrimary" onClick={()=>setMode('tenant')}>Cliente / constructora</button><button className="adminGhost" onClick={()=>setMode('platform')}>Platform Owner</button></div></div></main>;if(!key.trim())return <Login title={mode==='tenant'?'Workspace cliente':'Platform Owner'} subtitle={mode==='tenant'?'Clave de acceso de la constructora.':'Clave maestra de plataforma.'} value={key} setValue={setKey} onSubmit={()=>{if(!key.trim())setError('La clave es obligatoria')}} error={error} onBack={reset}/>;return mode==='tenant'?<TenantPortal apiKey={key} onLogout={reset}/>:<PlatformPortal platformKey={key} onLogout={reset}/>;}
