import { useEffect, useMemo, useState } from 'react';
import './admin.css';
import ProjectBuilder from './ProjectBuilder';
const API = import.meta.env.VITE_API_BASE_URL || '/api';
const request=async(path,options={})=>{const r=await fetch(`${API}${path}`,options);const d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.message||`Error ${r.status}`);return d};
const json=(method,body,headers)=>({method,headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify(body)});
const Field=({label,...p})=><label className="adminField"><span>{label}</span><input {...p}/></label>;
const Notice=({children})=>children?<div className="adminNotice">{children}</div>:null;
function Login({value,setValue,onSubmit,error}){return <main className="adminLogin"><div className="loginBox"><span className="adminLogo">RE</span><span className="adminKicker">REALESTATE · CLIENTE</span><h1>Espacio de la constructora</h1><p>Gestioná únicamente los proyectos de tu empresa.</p><form onSubmit={e=>{e.preventDefault();onSubmit()}}><Field label="Clave de acceso" type="password" value={value} onChange={e=>setValue(e.target.value)} required/><button className="adminPrimary">Entrar</button></form><Notice>{error}</Notice></div></main>}
function Shell({company,onLogout,children}){return <div className="adminApp"><header className="adminHeader"><div><b>RE</b><strong>{company?.name||'Constructora'}</strong><small>Espacio de cliente</small></div><button className="adminGhost" onClick={onLogout}>Salir</button></header>{children}</div>}
function Workspace({apiKey,onLogout}){const headers=useMemo(()=>({'x-api-key':apiKey}),[apiKey]);const [company,setCompany]=useState(null),[projects,setProjects]=useState([]),[selected,setSelected]=useState(null),[form,setForm]=useState({name:'',slug:'',description:''}),[error,setError]=useState('');const load=async()=>{const [me,list]=await Promise.all([request('/admin/me',{headers}),request('/admin/projects',{headers})]);setCompany(me);setProjects(list)};useEffect(()=>{load().catch(e=>setError(e.message))},[apiKey]);const create=async e=>{e.preventDefault();try{const p=await request('/admin/projects',json('POST',form,headers));setForm({name:'',slug:'',description:''});await load();setSelected(p)}catch(e){setError(e.message)}};if(selected)return <ProjectBuilder project={selected} apiKey={apiKey} onRefresh={load} onBack={()=>setSelected(null)}/>;return <Shell company={company} onLogout={onLogout}><main className="adminMain"><div className="workspaceHead"><div><span className="adminKicker">CLIENTE · WORKSPACE</span><h1>Mis proyectos</h1><p>Gestioná únicamente los proyectos, contenidos e inventario de tu empresa.</p></div></div><Notice>{error}</Notice><div className="contentGrid"><article className="adminPanel"><span className="adminKicker">NUEVO PROYECTO</span><h2>Crear proyecto</h2><form onSubmit={create}><Field label="Nombre" value={form.name} onChange={e=>setForm({...form,name:e.target.value})} required/><Field label="Slug" value={form.slug} onChange={e=>setForm({...form,slug:e.target.value})}/><label className="adminField"><span>Descripción</span><textarea value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><button className="adminPrimary">Crear proyecto</button></form></article><article className="adminPanel"><span className="adminKicker">PORTAFOLIO</span><h2>{projects.length} proyectos</h2>{projects.map(p=><button className="projectCard" key={p.id} onClick={()=>setSelected(p)}><b>{p.name}</b><span>{p.slug}</span><em>{p.status}</em></button>)}</article></div></main></Shell>}
function ClientGate({initialProject=null,shareToken=null}){const [key,setKey]=useState(''),[error,setError]=useState('');if(initialProject&&shareToken)return <ProjectBuilder project={initialProject} apiKey={shareToken} authHeader="x-share-token" onBack={()=>{window.location.href='/workspace'}}/>;if(!key.trim())return <Login value={key} setValue={setKey} onSubmit={()=>{if(!key.trim())setError('La clave es obligatoria')}} error={error}/>;return <Workspace apiKey={key} onLogout={()=>{setKey('');setError('')}}/>;}
export default function ClientPortal(props){return <ClientGate {...props}/>;}
